<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Asynchronous JavaScript</title>
</head>
<body>
    <h1>Asynchronous JavaScript</h1>
    <script>
        /*const second = () => {
            setTimeout(() => {
               console.log(`Async Hey There!!!`) 
            },2000);
            
        }
        const first = () => {
            console.log(`Hey There!!!`);
            second ();
            console.log('The end');
        }
        first();*/
        //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        //////Lecture:Asynchronous Javascript with Callback
        // *function getRecipe() {
        //     setTimeout(() => {
        //         const recipeID = [423, 567, 345, 200];
        //         console.log(recipeID);
        //         setTimeout((id) => {
        //             const recipe = {title: 'Tomato Sauce Pizza',
        //             publisher: 'Subhash'
        //             }
        //             console.log(`${id}: ${recipe.title} `);
        //             setTimeout((publisher) => {
        //                 const recipe2 = {
        //                     title: 'Sphagetti',
        //                     publisher: 'Subhash'
        //                 }
        //                 console.log(recipe2);
        //             }, 1500, recipe.publisher);
                    
        //         }, 1500, recipeID[2]);
        //     }, 1500);
        // }

        // getRecipe();*
        // //Imagine we have more and more and more chaining here like 10 levels then we would have all of these callbacks here inside of one another. that is so called callback hell.
        //this traingular shape is the sign of call back hell
        //call back hell: it means that we have call back inside of call back inside of callback, which after sometime gets really unmanageable.
        //Promises can avoid all of this call back hell here, and have a nicer and cleaner syntax when using asynchronous JS.
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Eg to produce and consume promises
// const getIDs = new Promise((resolve, reject ) => {
//     setTimeout(() => {
//         resolve([549, 453, 342, 541, 133]);
//     }, 1500 );
// });
// const getRecipe = recID => {
//     return new Promise((resolve, reject) => {
//         setTimeout((ID) => {
//             const recipe = {title: 'Tomato Sauce Pizza',
//             publisher: 'Subhash' }; 
//             resolve(`${ID}: ${recipe.title} `);
                    
//         }, 1500, recID);
//     })
// }
// const getPublish = publisher => {
//     return new Promise ((resolve, reject) => {
//         setTimeout((pub) => {
//             const recipe = {
//                 title: 'Sphagetti',
//                 publisher: 'Subhash'};
//                 resolve(`${publisher}: ${recipe.title} `);
//         }, 1500, publisher);
//     })
// }

// getIDs
// .then(IDs => {
//     console.log(IDs);
//     return getRecipe(IDs[2]);
// })
// .then(recipe => {
//     console.log(recipe);
//     return getPublish('Subhash');
// } )
// .then(recipe => {
//     console.log(recipe);
// })
// .catch(error => {
//     console.log('Error!!!');
// });
// async function getRecipeAW() {
//     const ID = await getIDs;
//     console.log(ID);
//     const recipe = await getRecipe(ID[2]);
//     console.log(recipe);
//     const publisherv= await getPublish('Subhash');
//     console.log(publisherv);

//     return recipe;

// }
// const rec = getRecipeAW();               //Reason written in notebook
// console.log(rec);
// getRecipeAW().then(result => {
//     console.log(`${result} is the best recipe`);
// });
function getWeather(woeid){
fetch(`https://crossorigin.me/https://www.metaweather.com/api/location/${woeid}/`)
.then( result => {
    console.log(result);
    return result.json();

})
.then( data => {
    //console.log(data);
    const today = (data.consolidated_weather[0]);
    console.log(`Temperature in ${data.title} stay between ${today.min_temp} and ${today.max_temp}.`);
})
.catch(error => console.log(error));

}
getWeather(2487956);
getWeather(44418);

async function getWeatherAW(woeid) {
    try {
        const result = await fetch(`https://crossorigin.me/https://www.metaweather.com/api/location/${woeid}/`)  ;
        const data = await result.json();
        const tomorrow = (data.consolidated_weather[1]);
        console.log(`Temperature in ${data.title} stay between ${tomorrow.min_temp} and ${tomorrow.max_temp}.`);
        return data;

    } catch (error){
        alert(error);
    }
        
}
let dataLondon;
getWeatherAW(2487956);
//let dataLondon = datagetWeatherAW(44418);                 this is not going to work like this because console log is done way earlier
//console.log(dataLondon);                                  and the promise result comes later as it works asynchronously.

getWeatherAW(44418).then(data => {
dataLondon = data ;
console.log(dataLondon);
});


    </script>
</body>
</html>